# Generated by Django 5.0.1 on 2024-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this user's email is verified. ", verbose_name='email_verified'),
        ),
    ]
